language: python

python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"

env:
  - DJANGO_VERSION=1.5
  - DJANGO_VERSION=1.6
  - DJANGO_VERSION=1.7
  - DJANGO_VERSION=1.8
  - DJANGO_VERSION=1.9
  - DJANGO_VERSION=3.0
  - DJANGO_VERSION=3.1
  - DJANGO_VERSION=3.2
  - DJANGO_VERSION=4.0
  - DJANGO_VERSION=4.1
  - DJANGO_VERSION=4.2

install:
  - pip install -q coveralls
  - pip install -q pytz==2015.7
  - pip install -q pillow
  - pip install -q django==$DJANGO_VERSION
  - pip install -q -e .

script:
  - coverage run --source=save_the_change setup.py test

after_success:
  - coveralls
